import { Inter } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify'; // Import ToastContainer
import 'react-toastify/dist/ReactToastify.css'; // Import Toastify CSS

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* ToastContainer to display toast notifications */}
                <ToastContainer
                    position="top-right" // Position where the toast appears
                    autoClose={5000} // Time before it auto-closes
                    hideProgressBar={false} // Show progress bar
                    newestOnTop={true} // Display the newest toast on top
                    closeOnClick // Allow closing on click
                    rtl={false} // Don't use right-to-left layout
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover // Pause toast when hovering
                />
                {children} {/* Render the children (other pages) */}
            </body>
        </html>
    );
}


